spring:
  application:
    name: soul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: acfuns
    password: 200011

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myRealm

server:
  port: 8081